default_hooks = dict(
    checkpoint=dict(interval=1, type="CheckpointHook"),
    logger=dict(interval=50, type="LoggerHook"),
    param_scheduler=dict(type="ParamSchedulerHook"),
    sampler_seed=dict(type="DistSamplerSeedHook"),
    timer=dict(type="IterTimerHook"),
    visualization=dict(type="DetVisualizationHook"),
)
default_scope = "visdet"
model = dict(
    backbone=dict(
        attn_drop_rate=0.0,
        convert_weights=True,
        depths=[
            2,
            2,
            18,
            2,
        ],
        drop_path_rate=0.3,
        drop_rate=0.0,
        embed_dims=96,
        frozen_stages=-1,
        mlp_ratio=4,
        num_heads=[
            3,
            6,
            12,
            24,
        ],
        out_indices=[
            0,
            1,
            2,
            3,
        ],
        patch_norm=True,
        qk_scale=None,
        qkv_bias=True,
        type="SwinTransformer",
        window_size=7,
        with_cp=False,
    ),
    data_preprocessor=dict(
        bgr_to_rgb=True,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        pad_mask=True,
        pad_size_divisor=32,
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type="DetDataPreprocessor",
    ),
    neck=dict(
        in_channels=[
            96,
            192,
            384,
            768,
        ],
        num_outs=5,
        out_channels=256,
        type="FPN",
    ),
    roi_head=dict(
        bbox_head=dict(
            bbox_coder=dict(
                target_means=[
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ],
                target_stds=[
                    0.1,
                    0.1,
                    0.2,
                    0.2,
                ],
                type="DeltaXYWHBBoxCoder",
            ),
            fc_out_channels=1024,
            in_channels=256,
            loss_bbox=dict(loss_weight=1.0, type="L1Loss"),
            loss_cls=dict(loss_weight=1.0, type="CrossEntropyLoss", use_sigmoid=False),
            num_classes=69,
            reg_class_agnostic=False,
            roi_feat_size=7,
            type="Shared2FCBBoxHead",
        ),
        bbox_roi_extractor=dict(
            featmap_strides=[
                4,
                8,
                16,
                32,
            ],
            out_channels=256,
            roi_layer=dict(output_size=7, sampling_ratio=0, type="RoIAlign"),
            type="SingleRoIExtractor",
        ),
        mask_head=dict(
            conv_out_channels=256,
            in_channels=256,
            loss_mask=dict(loss_weight=1.0, type="CrossEntropyLoss", use_mask=True),
            num_classes=69,
            num_convs=4,
            type="FCNMaskHead",
        ),
        mask_roi_extractor=dict(
            featmap_strides=[
                4,
                8,
                16,
                32,
            ],
            out_channels=256,
            roi_layer=dict(output_size=14, sampling_ratio=0, type="RoIAlign"),
            type="SingleRoIExtractor",
        ),
        type="StandardRoIHead",
    ),
    rpn_head=dict(
        anchor_generator=dict(
            ratios=[
                0.5,
                1.0,
                2.0,
            ],
            scales=[
                8,
            ],
            strides=[
                4,
                8,
                16,
                32,
                64,
            ],
            type="AnchorGenerator",
        ),
        bbox_coder=dict(
            target_means=[
                0.0,
                0.0,
                0.0,
                0.0,
            ],
            target_stds=[
                1.0,
                1.0,
                1.0,
                1.0,
            ],
            type="DeltaXYWHBBoxCoder",
        ),
        feat_channels=256,
        in_channels=256,
        loss_bbox=dict(loss_weight=1.0, type="L1Loss"),
        loss_cls=dict(loss_weight=1.0, type="CrossEntropyLoss", use_sigmoid=True),
        type="RPNHead",
    ),
    test_cfg=dict(
        rcnn=dict(mask_thr_binary=0.5, max_per_img=100, nms=dict(iou_threshold=0.5, type="nms"), score_thr=0.05),
        rpn=dict(max_per_img=1000, min_bbox_size=0, nms=dict(iou_threshold=0.7, type="nms"), nms_pre=1000),
    ),
    train_cfg=dict(
        rcnn=dict(
            assigner=dict(
                ignore_iof_thr=-1,
                match_low_quality=True,
                min_pos_iou=0.5,
                neg_iou_thr=0.5,
                pos_iou_thr=0.5,
                type="MaxIoUAssigner",
            ),
            debug=False,
            mask_size=28,
            pos_weight=-1,
            sampler=dict(add_gt_as_proposals=True, neg_pos_ub=-1, num=512, pos_fraction=0.25, type="RandomSampler"),
        ),
        rpn=dict(
            allowed_border=-1,
            assigner=dict(
                ignore_iof_thr=-1,
                match_low_quality=True,
                min_pos_iou=0.3,
                neg_iou_thr=0.3,
                pos_iou_thr=0.7,
                type="MaxIoUAssigner",
            ),
            debug=False,
            pos_weight=-1,
            sampler=dict(add_gt_as_proposals=False, neg_pos_ub=-1, num=256, pos_fraction=0.5, type="RandomSampler"),
        ),
        rpn_proposal=dict(max_per_img=1000, min_bbox_size=0, nms=dict(iou_threshold=0.7, type="nms"), nms_pre=2000),
    ),
    type="MaskRCNN",
)
optim_wrapper = dict(
    optimizer=dict(
        betas=[
            0.9,
            0.999,
        ],
        eps=1e-08,
        lr=0.0001,
        type="AdamW",
        weight_decay=0.05,
    )
)
train_cfg = dict(max_epochs=1, type="EpochBasedTrainLoop", val_interval=1)
train_dataloader = dict(
    batch_size=2,
    dataset=dict(
        ann_file="cmr/annotations/2025-05-15_12:38:23.077836_train_ordered.json",
        data_prefix=dict(img="images/"),
        data_root="/home/georgepearse/data/",
        metainfo=dict(
            classes=[
                "TR133R Mercury Battery",
                "Default",
                "Unknown Battery",
                "LiMNO2 Single Cell Battery",
                "C_D_Carbon Zinc Battery",
                "6V Alkaline Battery Casing",
                "6V Carbon Zinc Battery Casing",
                "Multicell NiMH Battery Pack",
                "C_D Alkaline Battery",
                "AA Lithium Ion Battery",
                "Button Alkaline Battery",
                "6V Lead Acid Battery Casing",
                "9V Lithium Metal Battery",
                "Burgess",
                "AA_AAA Alkaline Battery",
                "9V Alkaline Battery",
                "Lithium Iron Phosphate Battery",
                "CR_AA_AAA Lithium Metal",
                "AAA Zinc Chloride Battery",
                "Multicell Lithium Ion Battery Pack",
                "2.4V NiMH Battery",
                "AA_AAA_or_2-3V_NiCd NiMH Battery",
                "Lithium Polymer Battery",
                "Conveyor Belt Metal",
                "C_D_Lithium Metal Battery",
                "3.5V NiCd Battery",
                "Carbon Zinc Burgess",
                "4.5V Carbon Zinc Battery",
                "3V_3.6V_3.7V_Lithium Ion Battery",
                "Lead Acid Battery",
                "C NiCd_NiMH Battery",
                "3.6V NiMH Battery",
                "Multicell Carbon Zinc Battery Pack",
                "Battery Components",
                "Random Metal Object",
                "Crushed Battery Casing",
                "D NiCd Battery",
                "2.5V NiCd Battery",
                "9V NiCd Battery",
                "AA_AAA Carbon Zinc Battery",
                "Multicell Lead Acid Battery Pack",
                "Button Lithium Metal Battery",
                "2CR5 Lithium Metal Battery Casing",
                "Small 3.7V Lithium Ion Battery",
                "D NiMH Battery",
                "Button NiMH Battery",
                "RCR2 Lithium Phosphate Battery",
                "1.5V Alkaline Battery",
                "Multicell Alkaline Battery Pack",
                "9V NiMH Battery",
                "Coin",
                "Button Silver Oxide Battery",
                "Button Zinc Air Battery",
                "9.6V NiMH Battery",
                "1.5V Carbon Zinc Battery",
                "AA Lithium Phosphate Battery",
                "Multicell Lithium Metal Battery Pack",
                "9V Carbon Zinc Battery",
                "4.5V Alkaline Battery",
                "RCR123A Lithium Phosphate Battery",
                "AA Lithium Iron Battery",
                "AAAA_23A_LR1 Alkaline Battery",
                "LiMNO2 MultiCell Battery Pack",
                "Multicell NiCd Battery Pack",
                "12V Carbon Zinc Battery Casing",
                "Battery Connector Wire",
                "Multicell Silver Oxide Battery Pack",
                "TR133R NiCd Battery",
                "Lithium Ion Battery",
            ]
        ),
        pipeline=[
            dict(type="LoadImageFromFile"),
            dict(type="LoadAnnotations", with_bbox=True, with_mask=True),
            dict(
                keep_ratio=True,
                scale=[
                    1333,
                    800,
                ],
                type="Resize",
            ),
            dict(prob=0.5, type="RandomFlip"),
            dict(type="PackDetInputs"),
        ],
        type="CocoDataset",
    ),
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=True, type="DefaultSampler"),
)
val_cfg = None
val_dataloader = None
val_evaluator = None
work_dir = "./work_dirs/cmr_test"
